### ISSUE TITLE
changing status in setRefreshing doesn't failing the test!

### ISSUE THREAD

**Issue by m-awadi** [googlecodelabs/android-testing#11]
In Unit test Test Artifact, class NotesPresenterTest , loadNotesFromRepositoryAndLoadIntoView testcase:

verify(mNotesView).setProgressIndicator(false);

when flipping false to true, it still passing the test ! even it get called from presenter with false!

to validate that do the following,
verify(mNotesView).setProgressIndicator(false);
verify(mNotesView).setProgressIndicator(true);
verify(mNotesView).setProgressIndicator(false);

it still pass!, not sure where is the bug!

**Comment by slinzner** [comment]
It works as intended. Both of these methods are called in loadNotes(). Once before load the data from the repository (setProgressIndicator(true)) and after setProgressIndicator(false) when we get the callback. So when you verify the interaction both verifications are true in this case. The correct way of verifying this behavior would probably be to use Mockito InOrder API. I might add it in a future release if it does not add to much complexity to the test, since this is still  a sample app.
